apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

bases:
  - ../../base

# Override replica count and resource limits for dev (smaller footprint)
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: api-service
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
    target:
      kind: HorizontalPodAutoscaler
      name: api-service-hpa

commonLabels:
  environment: dev
