apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - serviceaccount.yml
  - config.yml
  - networkpolicy.yml
  - pod.yml
  - service.yml
  - ingress.yml
  - hpa.yml
  - pdb.yml
