apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-sa
  namespace: microservices
  labels:
    app.kubernetes.io/name: microservices-sa
  annotations:
    # Workload Identity — links this SA to an Azure Managed Identity
    # Replace with the actual client ID of your User-Assigned Managed Identity
    azure.workload.identity/client-id: "c4019192-67d1-4759-ba61-6cfe5fabdc6c"
automountServiceAccountToken: false
